import fs from "fs";
import path from "path";

const postDir = "hugo-site/content/posts";
if (!fs.existsSync(postDir)) fs.mkdirSync(postDir, { recursive: true });

const file = path.join(postDir, `auto-${Date.now()}.md`);

const content = `---
title: "Auto Generated Blog"
date: ${new Date().toISOString()}
---

This is your first **fully automated blog post** generated by GitHub Actions 🚀
`;

fs.writeFileSync(file, content);
console.log("Blog generated:", file);
